name: Feature request
description: Suggest an improvement or a new feature.
labels: ["enhancement"]
body:
  - type: textarea
    id: need
    attributes:
      label: Need
      description: The problem you face or what you want to achieve.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
